name: Testing
on: push #when should this workflow run

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run:
        pip install Django == 3.0.9
        python manage.py test